### ISSUE TITLE
Color settings not applying in backend

### ISSUE THREAD

**Issue by nickfmc** [pagelab/current-year#1]
If I set the color settings on the dynamic year block it applies to the frontend of my site as expected but not the backend editor preview

**Comment by pagelab** [comment]
Hey @nickfmc,

I conducted some testing on a fresh WP installation using the latest plugin version (0.6.1) and could not reproduce this issue. There were indeed some issues in the previous versions, but they have been sorted out recently.

Could you check if your plugin is on the latest version?

**Comment by pagelab** [comment]
Since I haven't heard from you for some time, I'll go ahead and close this one. Feel free to open it again if needed.
