### ISSUE TITLE
Text Color not changing

### ISSUE THREAD

**Issue by juanraortiz** [pagelab/current-year#2]
Hi Marcio. Thank for creating such a great plugin.

I'm using your Dynamic Year Block plugin but found that the color before and after are not changing when setting the text color. Check the gif image I just attached. I cleared the Cache, tried clean install, and yet can't change the color. This happen in the back and front end.

Is it my configuration or is it a bug in the plugin? Please let me know. 

I'm using the container that comes with Spectra (the same guys from Astra) but I tested the group block and the problem still persist.

I'm using Spectra One block theme too. 

![Untitled](https://github.com/EpicoStudio/dynamic-year-block/assets/68228361/d59d1763-090a-4028-b232-f4cb3ff736a0)

**Comment by pagelab** [comment]
Hi Juan,

I could not reproduce this error on my side. You can test it yourself on this [WordPress Playground.](https://playground.wordpress.net/?plugin=dynamic-year-block)

It's probably something on your side, like your theme or other plugin overriding the text color, but feel free to send me the URL of the site and more info about your setup, so I can have a look.

You can do that by using the Site Health Tool, which you can find in your WordPress admin:

- Access the Site Health page in your WordPress admin area under Tools » Site Health.
- Switch to the 'Info' tab to find essential system data neatly organized.
- Click 'Copy to Clipboard' to easily share all information or expand categories for specific details like PHP version or file upload limits.

After that, paste it here, so I can have a better idea of your environment.

Take care.

**Comment by pagelab** [comment]
Since I haven't heard from you for some time, I'll go ahead and close this one. Feel free to open it again if needed.
